import cv2
img=cv2.imread('sat.jpg')
r=cv2.resize(img,(500,350))
rot=cv2.getRotationMatrix2D((r.shape[1]/2,r.shape[0]/2),30,1)
rotated=cv2.warpAffine(r,rot,(r.shape[1],r.shape[0]))
cv2.imshow('Original',img)
cv2.imshow('Risized',r)
cv2.imshow('rotated',rotated)
cv2.waitKey(0)
cv2.destroyAllWindows()
